local_costmap:
  global_frame: odom
  robot_base_frame: base_link
  update_frequency: 20.0
  publish_frequency: 5.0

  # <-- Increase these to cover your laser origin
  width: 6.0     # meters
  height: 6.0    # meters

  plugins:
    - {name: obstacle_layer, type: "nav2_costmap_2d::ObstacleLayer"}
    - {name: inflation_layer, type: "nav2_costmap_2d::InflationLayer"}

obstacle_layer:
  # point this at your laser frame:
  observation_sources: laser
  laser:
    sensor_frame: laser_frame
    data_type: LaserScan
    topic: /scan
    marking: true
    clearing: true
    min_obstacle_height: 0.0
    max_obstacle_height: 2.0
